# Generated by Django 4.1.6 on 2023-02-03 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smallurl', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='original_url',
            new_name='url',
        ),
    ]
