# Generated by Django 4.1.6 on 2023-02-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smallurl', '0002_rename_original_url_url_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='tls',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
