# Generated by Django 4.1.6 on 2023-02-05 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smallurl', '0005_url_expire_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='expire_time',
            new_name='expires',
        ),
    ]
