# Generated by Django 4.1.6 on 2023-02-05 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smallurl', '0006_rename_expire_time_url_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='url',
            field=models.URLField(),
        ),
    ]
