# Generated by Django 4.1.6 on 2023-02-06 00:02

from django.db import migrations, models
import smallurl.models


class Migration(migrations.Migration):

    dependencies = [
        ('smallurl', '0007_alter_url_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='id',
            field=models.CharField(default=smallurl.models.idgen, max_length=50, primary_key=True, serialize=False),
        ),
    ]
